[package]
name = "engine-core"
version = "0.1.0"
edition = "2024"

[dependencies]
aide = { version = "0.14.2", features = ["axum"] }
alloy = { version = "1.0.8", features = ["serde"] }
schemars = "0.8.22"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
vault-types = { version = "0.1.0", git = "ssh://git@github.com/thirdweb-dev/vault.git", branch = "main" }
vault-sdk = { version = "0.1.0", git = "ssh://git@github.com/thirdweb-dev/vault.git", branch = "main" }
tower = "0.5.2"
tracing = "0.1.41"
async-nats = "0.40.0"
twmq = { version = "0.1.0", path = "../twmq" }
uuid = { version = "1.17.0", features = ["v4"] }
